### ISSUE TITLE
zk-stats-daemon won't start 0.1.8

### ISSUE THREAD

**Issue by mmichie** [twitter/zktraffic#68]
Any suggestions to troubleshooting this one?

$ sudo zk-stats-daemon  --version
Writing log files to disk in /var/tmp
0.1.8

```
$ sudo zk-stats-daemon  --aggregation-depth=5
Writing log files to disk in /var/tmp
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twitter/common/app/application.py", line 758, in _wrap_method
    return_code = method()
  File "/usr/lib/python2.7/dist-packages/twitter/common/app/application.py", line 780, in <lambda>
    main = lambda: main_method(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/zktraffic/cli/stats_daemon.py", line 140, in main
    server.run(opts.http_addr, opts.http_port)
  File "/usr/lib/python2.7/dist-packages/twitter/common/http/server.py", line 262, in run
    self._app.run(host=hostname, port=port, server=server)
AttributeError: 'Bottle' object has no attribute 'run'
```

**Comment by mmichie** [comment]
To follow up, looks like it fails on Bottle 0.10.9, but works fine on 0.12.9, the issue was a system bottle on the sys.path, looks like my error :8ball:
